### ISSUE TITLE
support for graylog 2.0 ?

### ISSUE THREAD

**Issue by kaililleby** [Graylog2/plugin-output-splunk#2]
this plugin doesn't seem to work with the graylog 2.0 beta releases - am i doing some thing wrong or are the graylog 1.x plugins not compatible with graylog 2 ?

**Comment by luratech** [comment]
works with the latest commits from 27 Apr -> download sources and build with maven.

**Comment by joschi** [comment]
I've just release version 0.4.0 of this plugin which added compatibility with Graylog 2.0.x.
